export const myImageList = {
  himanshu: "/assets/himanshu.png",
  html: "/assets/html.png",
  css: "/assets/css.png",
  js: "/assets/javascript.png",
  jquery: "/assets/jquery.png",
  react: "/assets/react.png",
  nextjs: "/assets/nextjs.png",
  tailwind: "/assets/tailwind.png",
  node: "/assets/node.png",
  bootstrap: "/assets/bootstrap.png",
  github: "/assets/github.png",
  githubDark: "/assets/githubDark.png",
  agile: "/assets/agile.png",
};
